# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter beyond0qlte,$(TARGET_DEVICE)),)

endif
